version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - 8123:8123
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}

volumes:
  postgres_data:
  clickhouse-data: